// Generated by ts-to-zod
import { z } from "https://deno.land/x/zod/mod.ts";

export const testSchema = z.object({
    myTest: z.number(),
    impNullable: z.number().optional(),
    expNullable: z.union([z.number(), z.undefined()])
});
